import styles from '../components/Home/home.module.scss'
import HomeComponent from '@/components/Home'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function Home() {
  return (
    <main className={styles.main}>
      <HomeComponent />
    </main>
  )
}
